### PR TITLE
WIP: Added docker stuff

### PR DESCRIPTION
**Pull request by rimi-itk**
First stab at putting this into a Docker container.

TO DO: Probably a lot …

### CODE REVIEW

**Comment by thomasjohansen** [comment]
Shouldn't it be multiple containers instead of running it in a single one?

**Comment by rimi-itk** [comment]
Maybe, I'm new to this – but I'm open for suggestions!

**Comment by thomasjohansen** [comment]
Do you guys use docker-compose for local environment?

**Comment by rimi-itk** [comment]
Yes, we use docker-composer for local development. I've discussed your comment with @cableman and we agree that we should not run everything inside one container.

However, it may make sense to have an ”all included box”, i.e. the one we have now, that makes it easy to pull in search_node for local development or testing.

**Pull request closed without merging**
